const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Frezer',
      slug: 'Hier tamcool',
      category: 'Fridge',
      image: '/images/box1.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Chinese-Couch',
      slug: 'Couch',
      category: 'Couch',
      image: '/images/box2.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'cooking pot',
      slug: 'cooking pot',
      category: 'pot',
      image: '/images/box3.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Huar',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'British Mattress',
      slug: 'British Mattress',
      category: 'Mattress',
      image: '/images/box4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'hawai',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Desktop monitor',
      slug: 'Desktop monitor',
      category: 'Desktop',
      image: '/images/box5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'HP',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Coffee Table',
      slug: 'Coffee Table',
      category: 'Table',
      image: '/images/tab8.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Table',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
